[package]
name = "flamenco687/error"
description = "Roblox library to quickly throw out clean & detailed errors"

version = "1.1.0"
license = "MIT License"

authors = ["flamenco687"]
realm = "shared"

registry = "https://github.com/UpliftGames/wally-index"

exclude = [
    "docs", 
    "foreman.toml",
    "test.project.json",
    "README.md",
    "LICENSE"
]